sonar.projectKey=hospital-management
sonar.projectName=Hospital Management System
sonar.projectVersion=1.0

sonar.sources=app
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=your-sonar-token